### ISSUE TITLE
Inbuild Magisk-Manager can't detect Magisk

### ISSUE THREAD

**Issue by Niemandausduisburg** [SHRP/platform_manifest_twrp_omni#2]
Hello,

the inbuild Magisk-Manager can install Magisk but can't detect Magisk and can't install any Modules.

**Comment by techyminati** [comment]
Can U please take logs & send dogbin of logs, 

Thanks

**Comment by Niemandausduisburg** [comment]
It works now. I had to format data and flash SHRP again.

**Comment by techyminati** [comment]
Okay Nice !
